import 'package:flutter/foundation.dart';

class AppStrings {
  static final ValueNotifier<String> languageNotifier = ValueNotifier('es');

  static String get currentLanguage => languageNotifier.value;

  static void setLanguage(String languageCode) {
    if (_localizedValues.containsKey(languageCode)) {
      languageNotifier.value = languageCode;
    }
  }

  static String get(String key) {
    return _localizedValues[currentLanguage]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'es': {
      // Login
      'loginTitle': 'Inicio de sesión',
      'userLabel': 'Usuario',
      'userHint': 'usuario@ejemplo.com',
      'passwordLabel': 'Contraseña',
      'passwordHint': '**********',
      'keepSession': 'Mantener sesión',
      'loginButton': 'INICIAR SESIÓN',
      'recoverPassword': 'Recuperar contraseña',
      'recoverTitle': 'Recuperar Contraseña',
      'recoverDescription': 'Ingresa tu correo electrónico y te enviaremos las instrucciones para restablecer tu contraseña.',
      'emailLabel': 'Correo Electrónico',
      'emailHint': 'ejemplo@correo.com',
      'sendInstructions': 'ENVIAR INSTRUCCIONES',
      'instructionsSent': 'Se han enviado las instrucciones a tu correo',
      'selectLanguage': 'Seleccionar Idioma',
      'spanish': 'Español',
      'english': 'Inglés',
      
      // Drawer / Menu
      'menuTitle': 'Menú',
      'lostObjects': 'Objetos Perdidos',
      'suggestions': 'Sugerencias',
      'survey': 'Encuesta',
      'information': 'Información',
      'announcements': 'Comunicados',
      'regulations': 'Reglamentación',
      'userManual': 'Manual de Usuario',
      'profile': 'Perfil',
      'logout': 'Cerrar Sesión',
      'logoutConfirmTitle': 'Cerrar Sesión',
      'logoutConfirmMsg': '¿Estás seguro de que deseas cerrar sesión?',
      'cancel': 'Cancelar',
      'accept': 'Aceptar',
      'stops': 'Paradas',
      'assistance': 'Asistencia',
      
      // Maps View
      'selectRoute': 'Seleccionar Ruta',
      'selectRouteMsg': 'Seleccione una ruta',
      'noRouteSelected': 'Sin ruta seleccionada',
      'routeActive': 'Ruta Activa',
      'outOfSchedule': 'Fuera de horario',
      'frequent': 'FRECUENTES',
      'onTime': 'EN TIEMPO',
      'all': 'TODAS',
      'mapTypeNormal': 'Normal',
      'mapTypeSatellite': 'Satélite',
      'mapTypeHybrid': 'Híbrido',
      'availableSchedules': 'Horarios disponibles para',
      'entries': 'Entradas',
      'exits': 'Salidas',
      'viewSchedules': 'Ver horarios',
      'selected': 'Seleccionaste',

      // Profile View
      'personalInfo': 'Información Personal',
      'supportPhone': 'Tel. de Soporte',
      'qrCode': 'Código QR',
      'comingSoon': 'Próximamente',
      'deleteAccount': 'Eliminar Cuenta',
      'deleteAccountMsg': '¿Estás seguro de que deseas eliminar tu cuenta? Esta acción no se puede deshacer.',
      'delete': 'Eliminar',

      // Lost Objects View
      'reportLostObject': 'Reportar Objeto Perdido',
      'fillFormMsg': 'Completa el formulario para reportar tu objeto',
      'nameLabel': 'Nombre Completo',
      'nameHint': 'Ingresa tu nombre completo',
      'nameError': 'Por favor ingresa tu nombre',
      'phoneLabel': 'Teléfono de Contacto',
      'phoneHint': 'Ingresa tu número de teléfono',
      'phoneError': 'Por favor ingresa tu teléfono',
      'phoneInvalid': 'Ingresa un número válido',
      'routeLabel': 'Ruta',
      'selectRouteHint': 'Selecciona la ruta',
      'routeError': 'Por favor selecciona una ruta',
      'dateLabel': 'Fecha del Incidente',
      'selectDate': 'Seleccionar fecha',
      'dateError': 'Por favor selecciona una fecha',
      'descriptionLabel': 'Descripción del Objeto',
      'descriptionHint': 'Describe el objeto con el mayor detalle posible...',
      'descriptionError': 'Por favor describe el objeto',
      'descriptionLengthError': 'La descripción debe tener al menos 10 caracteres',
      'submitReport': 'ENVIAR REPORTE',
      'reportSent': 'Reporte enviado correctamente',
      'fillAllFields': 'Por favor completa todos los campos',

      // Suggestions View
      'suggestionsBox': 'Buzón de Sugerencias',
      'yourSuggestionsMatters': 'Tus Sugerencias Importan',
      'helpUsImprove': 'Ayúdanos a mejorar nuestro servicio',
      'selectRouteLabel': 'Selección de Ruta',
      'selectScheduleLabel': 'Selección de Horario',
      'selectScheduleHint': 'Selecciona el horario',
      'scheduleError': 'Por favor selecciona un horario',
      'unitLabel': 'Unidad',
      'unitHint': 'Número de unidad',
      'unitError': 'Por favor ingresa el número de unidad',
      'commentLabel': 'Comentario o Sugerencia',
      'commentHint': 'Escribe tu comentario o sugerencia...',
      'commentError': 'Por favor escribe tu comentario',
      'commentLengthError': 'El comentario debe tener al menos 10 caracteres',
      'sendSuggestion': 'Enviar Sugerencia',
      'suggestionSent': 'Sugerencia enviada exitosamente',
      'scheduleLabel': 'Horario',

      // Survey View
      'serviceSurvey': 'Encuesta de Servicio',
      'satisfactionSurvey': 'Encuesta de Satisfacción',
      'yourOpinionHelps': 'Tu opinión nos ayuda a mejorar',
      'rateService': 'Califica el Servicio',
      'ratingScale': 'Del 1 (Malo) al 5 (Excelente)',
      'unitCleanliness': '1. Limpieza de las unidades',
      'operatorAttitude': '2. Actitud del operador',
      'operatorDriving': '3. Forma de conducir del operador',
      'bad': 'Malo',
      'excellent': 'Excelente',
      'sendSurvey': 'Enviar Encuesta',
      'surveySent': 'Encuesta enviada exitosamente. ¡Gracias!',
      'rateAllAspects': 'Por favor califica todos los aspectos',
    },
    'en': {
      // Login
      'loginTitle': 'Login',
      'userLabel': 'Username',
      'userHint': 'user@example.com',
      'passwordLabel': 'Password',
      'passwordHint': '**********',
      'keepSession': 'Keep me signed in',
      'loginButton': 'LOG IN',
      'recoverPassword': 'Recover password',
      'recoverTitle': 'Recover Password',
      'recoverDescription': 'Enter your email address and we will send you instructions to reset your password.',
      'emailLabel': 'Email Address',
      'emailHint': 'example@email.com',
      'sendInstructions': 'SEND INSTRUCTIONS',
      'instructionsSent': 'Instructions have been sent to your email',
      'selectLanguage': 'Select Language',
      'spanish': 'Spanish',
      'english': 'English',

      // Drawer / Menu
      'menuTitle': 'Menu',
      'lostObjects': 'Lost & Found',
      'suggestions': 'Suggestions',
      'survey': 'Survey',
      'information': 'Information',
      'announcements': 'Announcements',
      'regulations': 'Regulations',
      'userManual': 'User Manual',
      'profile': 'Profile',
      'logout': 'Log Out',
      'logoutConfirmTitle': 'Log Out',
      'logoutConfirmMsg': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'accept': 'Accept',
      'stops': 'Stops',
      'assistance': 'Assistance',

      // Maps View
      'selectRoute': 'Select Route',
      'selectRouteMsg': 'Select a route',
      'noRouteSelected': 'No route selected',
      'routeActive': 'Active Route',
      'outOfSchedule': 'Out of schedule',
      'frequent': 'FREQUENT',
      'onTime': 'ON TIME',
      'all': 'ALL',
      'mapTypeNormal': 'Normal',
      'mapTypeSatellite': 'Satellite',
      'mapTypeHybrid': 'Hybrid',
      'availableSchedules': 'Available schedules for',
      'entries': 'Entries',
      'exits': 'Exits',
      'viewSchedules': 'View schedules',
      'selected': 'Selected',

      // Profile View
      'personalInfo': 'Personal Information',
      'supportPhone': 'Support Phone',
      'qrCode': 'QR Code',
      'comingSoon': 'Coming Soon',
      'deleteAccount': 'Delete Account',
      'deleteAccountMsg': 'Are you sure you want to delete your account? This action cannot be undone.',
      'delete': 'Delete',

      // Lost Objects View
      'reportLostObject': 'Report Lost Object',
      'fillFormMsg': 'Fill out the form to report your object',
      'nameLabel': 'Full Name',
      'nameHint': 'Enter your full name',
      'nameError': 'Please enter your name',
      'phoneLabel': 'Contact Phone',
      'phoneHint': 'Enter your phone number',
      'phoneError': 'Please enter your phone number',
      'phoneInvalid': 'Enter a valid number',
      'routeLabel': 'Route',
      'selectRouteHint': 'Select route',
      'routeError': 'Please select a route',
      'dateLabel': 'Incident Date',
      'selectDate': 'Select date',
      'dateError': 'Please select a date',
      'descriptionLabel': 'Object Description',
      'descriptionHint': 'Describe the object in as much detail as possible...',
      'descriptionError': 'Please describe the object',
      'descriptionLengthError': 'Description must be at least 10 characters',
      'submitReport': 'SUBMIT REPORT',
      'reportSent': 'Report sent successfully',
      'fillAllFields': 'Please fill in all fields',

      // Suggestions View
      'suggestionsBox': 'Suggestion Box',
      'yourSuggestionsMatters': 'Your Suggestions Matter',
      'helpUsImprove': 'Help us improve our service',
      'selectRouteLabel': 'Route Selection',
      'selectScheduleLabel': 'Schedule Selection',
      'selectScheduleHint': 'Select schedule',
      'scheduleError': 'Please select a schedule',
      'unitLabel': 'Unit',
      'unitHint': 'Unit number',
      'unitError': 'Please enter the unit number',
      'commentLabel': 'Comment or Suggestion',
      'commentHint': 'Write your comment or suggestion...',
      'commentError': 'Please write your comment',
      'commentLengthError': 'Comment must be at least 10 characters',
      'sendSuggestion': 'Send Suggestion',
      'suggestionSent': 'Suggestion sent successfully',
      'scheduleLabel': 'Schedule',

      // Survey View
      'serviceSurvey': 'Service Survey',
      'satisfactionSurvey': 'Satisfaction Survey',
      'yourOpinionHelps': 'Your opinion helps us improve',
      'rateService': 'Rate the Service',
      'ratingScale': 'From 1 (Bad) to 5 (Excellent)',
      'unitCleanliness': '1. Unit cleanliness',
      'operatorAttitude': '2. Operator attitude',
      'operatorDriving': '3. Operator driving',
      'bad': 'Bad',
      'excellent': 'Excellent',
      'sendSurvey': 'Send Survey',
      'surveySent': 'Survey sent successfully. Thank you!',
      'rateAllAspects': 'Please rate all aspects',
    },
  };
}
